41:
	gcc 4.1.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 4.1
	./4.1

42:
	gcc 4.2.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 4.2
	./4.2

43:
	gcc 4.3.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 4.3
	./4.3