21:
	gcc 2.1.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.1
	./2.1

22:
	gcc 2.2.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.2
	./2.2

23:
	gcc 2.3.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.3
	./2.3

24:
	gcc 2.4.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.4
	./2.4


25:
	gcc 2.5.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.5
	./2.5


26:
	gcc 2.6.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.6
	./2.6

27:
	gcc 2.7.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.7
	./2.7

28:
	gcc 2.8.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.8
	./2.8

29:
	gcc 2.9.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.9
	./2.9

211:
	gcc 2.11.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.11
	./2.11

212:
	gcc 2.12.c -g -std=c99 -Wall -Wconversion -Wno-sign-conversion -Werror -o 2.12
	./2.12